### ISSUE TITLE
CLI arg to choose a model, and override parts of schedule

### ISSUE THREAD

**Issue by jayvdb** [morlandi/django-tables-cleaner#4] opened 2020-05-29 19:37 UTC
It would be nice to be able to run:

> clean_tables --keep_records=10 app[.model]

which would only process one app, or one model, still use any other rules, like `keep_since_days`, but ignores any existing `keep_records` value.  Usually this would be used to be more ruthless.

This would allow schedules to be created which are effectively infinite/disabled.

```py
    {
        'model': 'tasks.importantdata',
        'keep_records': 100000000,
        'keep_since_days': 1000000000,
        'get_latest_by': 'some_odd_field',
    },
```

It can then be cleaned in an adhoc manner, *using* the 'get_latest_by' value which may not be part of the third-party app's model metadata, and may be hard to remember.

**Comment by morlandi** [comment] 2020-09-14 09:28
@jayvdb , I'm trying to keep a "minimal approach" in these helper Django apps ;)
And since data loss is the worst thing that can happen, here I feel an extra need to be simple and safe.
This utility is more meant for production, where you need to squeeze some growing tables, but preserving the most recent records according to a pattern fixed by design.
In development, we already have so many simple ways to get rid of redundant data; my favorite one being:

    echo "delete from tablename" | python manage.py dbshell

**Closed by morlandi** 2020-09-14 09:28 UTC
